score:
  max: 100
  min: 0
  photo:
    empty_penalty: -10
    quality:
      high_definition: 20
      standard: 10
  irrelevant_threshold: 40
  description:
    empty: 0
    non_empty: 5
    length:
      default: 0
      flat:
        short: 0
        medium: 10
        large: 30
      chalet:
        large: 20
  keyword: 5
  full: 40